kind: Namespace
apiVersion: v1
metadata:
    name: {{ .Values.namespace | quote }}
    labels:
      istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-load-testing
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.domain | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: "virtual-load-testing"
spec:
  hosts:
    - {{ .Values.domain | quote }}
  gateways:
    - gateway-load-testing
  http:
  {{- range .Values.stacks }}
  - match:
    - uri:
        prefix: {{ printf "/%s" .name | quote }}
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ printf "svc-%s" .name | quote }}
    {{- end }}
---
