{{- $namespace := .Values.namespace -}}
{{- $replicaCount := .Values.replicaCount -}}
{{- range .Values.stacks }}
kind: Service
apiVersion: v1
metadata:
    namespace: {{ $namespace }}
    name: {{ printf "svc-%s" .name | quote }}
spec:
    selector:
        app: {{ printf "stack-%s" .name | quote }}
    ports:
        - protocol: TCP
          port: 80
          name: {{ printf "http-%s" .name | quote }}
          targetPort: {{ printf "p-%s" .name | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ $namespace }}
    name: {{ printf "dp-%s" .name | quote }}
spec:
    replicas: {{ $replicaCount }}
    selector:
        matchLabels:
            app: {{ printf "stack-%s" .name | quote }}
    template:
        metadata:
            namespace: {{ $namespace }}
            labels:
                app: {{ printf "stack-%s" .name | quote }}
        spec:
            containers:
                - name: {{ printf "app-%s" .name | quote }}
                  image: {{ .image | quote }}
                  ports:
                      - containerPort: {{ .port | default 9000 }}
                        name: {{ printf "p-%s" .name | quote }}
---
{{- end }}
