version: "3.7"
services:
  nginx:
    image: nginx:1.17.8
    ports:
      - "${EXPOSED_PORT}:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - "./server.php:/var/www/html/server.php"
    links:
        - php
  php:
    image: php:7.4.2-fpm-alpine
    volumes:
      - "./server.php:/var/www/html/server.php"
